name: Build architecture-specific images and push

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: linux/arm64
            registry: ghcr.io
            tag_suffix: arm64
          - arch: linux/amd64
            registry: docker.io
            tag_suffix: amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login Docker Hub
      - name: Login to Docker Hub
        if: matrix.registry == 'docker.io'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login GHCR
      - name: Login to GHCR
        if: matrix.registry == 'ghcr.io'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        env:
          SHORT_SHA: ${{ github.sha }}
          GH_OWNER: ${{ github.repository_owner }}
        run: |
          set -euo pipefail

          TAG="${SHORT_SHA:0:8}"

          if [ "${{ matrix.registry }}" = "ghcr.io" ]; then
            # ghcr.io/<owner>/<repo>
            IMAGE="ghcr.io/$GH_OWNER/${{ github.event.repository.name }}:${{ matrix.tag_suffix }}-$TAG"
          else
            # docker.io/<username>/<repo>
            IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.tag_suffix }}-$TAG"
          fi

          echo "Building for ${{ matrix.arch }} and pushing to $IMAGE"
          
          docker buildx build \
            --platform=${{ matrix.arch }} \
            -f ./Dockerfile \
            -t "$IMAGE" \
            --push .
